const GET_PARTICIPATIONS = 'GET_PARTICIPATIONS';
const SET_PARTICIPATIONS = 'SET_PARTICIPATIONS';
const REQUEST_PARTICIPATIONS = 'REQUEST_PARTICIPATIONS';
const POST_PARTICIPATIONS = 'POST_PARTICIPATIONS';

export default {
	GET_PARTICIPATIONS,
	SET_PARTICIPATIONS,
	REQUEST_PARTICIPATIONS,
	POST_PARTICIPATIONS
};
