const SET_PARTICIPATIONS = 'SET_PARTICIPATIONS';
const REQUEST_GET_PARTICIPATIONS = 'REQUEST_GET_PARTICIPATIONS';
const STOP_GET_PARTICIPATIONS = 'STOP_GET_PARTICIPATIONS';
const REQUEST_POST_PARTICIPATION = 'REQUEST_POST_PARTICIPATION';
const STOP_POST_PARTICIPATION = 'STOP_POST_PARTICIPATION';
const REQUEST_DELETE_PARTICIPATION = 'REQUEST_DELETE_PARTICIPATION';
const STOP_DELETE_PARTICIPATION = 'STOP_DELETE_PARTICIPATION';

export default {
	SET_PARTICIPATIONS,
	REQUEST_GET_PARTICIPATIONS,
	REQUEST_POST_PARTICIPATION,
	STOP_POST_PARTICIPATION,
	STOP_GET_PARTICIPATIONS,
	REQUEST_DELETE_PARTICIPATION,
	STOP_DELETE_PARTICIPATION
};
